#ifndef CONFIGS_HPP
#define CONFIGS_HPP

#ifndef MESH_TYPE
#define MESH_TYPE HalfEdgeMesh
#endif
#ifndef MESH_TYPE_HEADER
#define MESH_TYPE_HEADER <mesh_data/half_edge_mesh.hpp>
#endif
#ifndef TRIANGLE_COMPARATOR_BASE_T
#define TRIANGLE_COMPARATOR_BASE_T NullComparator
#endif
#ifdef TRIANGLE_COMPARATOR_WITH_ARGS
    #ifndef TRIANGLE_COMPARATOR_ASCENDING
    #define TRIANGLE_COMPARATOR_ASCENDING true
    #endif
    #ifndef TRIANGLE_COMPARATOR_SORT_PARAM_2
    #define TRIANGLE_COMPARATOR_SORT_PARAM_2 false
    #endif
    #define TRIANGLE_COMPARATOR TRIANGLE_COMPARATOR_BASE_T<MESH_TYPE,TRIANGLE_COMPARATOR_ASCENDING,TRIANGLE_COMPARATOR_SORT_PARAM_2>
#else 
    #define TRIANGLE_COMPARATOR TRIANGLE_COMPARATOR_BASE_T<MESH_TYPE>
#endif
#ifndef MERGING_STRATEGY_T
#define MERGING_STRATEGY_T ExcludePreviousCavitiesStrategy
#endif
#define MERGING_STRATEGY MERGING_STRATEGY_T<MESH_TYPE>
#ifndef SELECTION_CRITERION_T
#define SELECTION_CRITERION_T NullSelectionCriterion
#endif
#define SELECTION_CRITERION SELECTION_CRITERION_T<MESH_TYPE>
#ifdef SELECTION_CRITERION_WITH_ARG
    #define SELECTION_CRITERION_CONSTRUCTOR(ARG) SELECTION_CRITERION_T<MESH_TYPE>(ARG)
#endif
#ifndef GENERATOR_T
#define GENERATOR_T DelaunayCavityGenerator
#endif
#ifdef DELAUNAY_GENERATOR
    #define MESH_GENERATOR GENERATOR_T<MESH_TYPE, SELECTION_CRITERION, TRIANGLE_COMPARATOR, MERGING_STRATEGY>
#else
    #define MESH_GENERATOR GENERATOR_T<MESH_TYPE> // Polylla
#endif

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#endif //CONFIGS_HPP