#ifndef MESH_STAT_HPP
#define MESH_STAT_HPP

enum MeshStat {
    N_POLYGONS,
    N_FRONTIER_EDGES,
    N_BARRIER_EDGE_TIPS,
    N_POLYGONS_TO_REPAIR,
    N_POLYGONS_ADDED_AFTER_REPAIR,
    N_VERTICES,
    N_EDGES,
    N_BORDER_EDGES
};

#endif