#ifndef TIME_STAT_HPP
#define TIME_STAT_HPP

enum TimeStat {
    T_TRIANGULATION_GENERATION,
    T_LABEL_MAX_EDGES,
    T_LABEL_FRONTIER_EDGES,
    T_LABEL_SEED_EDGES,
    T_TRAVERSAL_AND_REPAIR,
    T_TRAVERSAL,
    T_REPAIR
};

#endif